name:                haskell2
version:             0.1.0.0
github:              "githubuser/haskell2"
license:             MIT
author:              "Cristian Inthamoussu"
maintainer:          "cinthamo@gmail.com"
copyright:           "2021 Cristian Inthamoussu"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell2#readme>

dependencies:
- base >= 4.7 && < 5
- antlr-haskell >= 0.1
- containers >= 0.6.5.1
- pretty-simple >= 4.0.0.0

library:
  source-dirs: src

default-extensions:
  - DeriveLift
  - DeriveDataTypeable
  - DeriveGeneric
  - DeriveAnyClass
  - QuasiQuotes
  - TemplateHaskell
  - ScopedTypeVariables
  - OverloadedStrings
  - FlexibleContexts
  - TypeFamilies