name:                haskell2
version:             0.1.0.0
github:              "cinthamo/property-model"
license:             MIT
author:              "Cristian Inthamoussu"
maintainer:          "cinthamo@gmail.com"
copyright:           "2022 Cristian Inthamoussu"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/cinthamo/property-model#readme>

dependencies:
- base >= 4.7 && < 5
- antlr-haskell >= 0.1
- containers >= 0.6.5.1
- shelly >= 1.9.0
- pretty-simple >= 4.0.0.0
- HStringTemplate >= 0.8.8
- string-interpolate >= 0.3.1
- unordered-containers >= 0.2.14

library:
  source-dirs: src

executables:
  f:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell2

default-extensions:
  - DeriveLift
  - DeriveDataTypeable
  - DeriveGeneric
  - DeriveAnyClass
  - QuasiQuotes
  - TemplateHaskell
  - ScopedTypeVariables
  - OverloadedStrings
  - FlexibleContexts
  - TypeFamilies